package(default_visibility = ["//visibility:public"])


cc_library(
    name = 'nlohmann',
    hdrs = glob([
        "*.h",
        "*/*.h",
        "**/*.h",
    ]),
    srcs = glob([
        "*.hpp",
        "*/*.hpp",
        "**/*.hpp",
    ],
    exclude = [
    ]),
    copts = [
    ],
    deps = [
 
    ],

)
